### ISSUE TITLE
Question about your study resources

### ISSUE THREAD

**Issue by devRayanwv** [rodolfobandeira/php-certification-studies#8]
Hi, 
congrats for passing the exam. I have question about your study resources. What material did you study from. I am planning to take the exam this summer but I have no idea how to study for the exam. Any tips or ideas are highly appreciated.

Thank you

**Comment by rodolfobandeira** [comment]
Hi @devRayanwv, Sorry for the late response. Here are my tips:

1) Download http://ankisrs.net/ and study some PHP Flashcards. They have one only for php certification;
2) I bought the study guide from Zend (It was around $30). I printed it and studied every page.
3) I tried to solve some questions from a Brazilian PHP Certification Group:  (http://rumoacertificacaophp.com). Most of the questions are in English, so.. it really helps!!
4) I was saving here in this repository some examples. I'm still using this repository as reference when I don't remember some php syntax or function usage.

Good luck!
